"""empty message

Revision ID: 08bdd0f9366e
Revises: 834b1a697901
Create Date: 2020-07-17 15:11:26.262986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bdd0f9366e'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_fname'), 'user', ['fname'], unique=True)
    op.create_index(op.f('ix_user_lname'), 'user', ['lname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lname'), table_name='user')
    op.drop_index(op.f('ix_user_fname'), table_name='user')
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###
