"""empty message

Revision ID: 3b01f22f6621
Revises: 1289ac23261a
Create Date: 2020-08-02 19:34:12.007493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b01f22f6621'
down_revision = '1289ac23261a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###
