"""empty message

Revision ID: 4663765be30c
Revises: 310fd75211bd
Create Date: 2020-08-13 20:06:19.682886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4663765be30c'
down_revision = '310fd75211bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###
