"""empty message

Revision ID: 743a47620200
Revises: 3b01f22f6621
Create Date: 2020-08-03 20:10:57.157429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743a47620200'
down_revision = '3b01f22f6621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('place_of_work', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('portfolio', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'portfolio')
    op.drop_column('user', 'place_of_work')
    # ### end Alembic commands ###
