"""empty message

Revision ID: 8a3ddd158c58
Revises: 743a47620200
Create Date: 2020-08-03 20:24:06.532139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3ddd158c58'
down_revision = '743a47620200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('position', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    # ### end Alembic commands ###
