"""empty message

Revision ID: edde1de40e64
Revises: 1d2c4b957b4d
Create Date: 2020-08-01 10:42:35.559463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edde1de40e64'
down_revision = '1d2c4b957b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_fname', table_name='user')
    op.create_index(op.f('ix_user_fname'), 'user', ['fname'], unique=False)
    op.drop_index('ix_user_lname', table_name='user')
    op.create_index(op.f('ix_user_lname'), 'user', ['lname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lname'), table_name='user')
    op.create_index('ix_user_lname', 'user', ['lname'], unique=1)
    op.drop_index(op.f('ix_user_fname'), table_name='user')
    op.create_index('ix_user_fname', 'user', ['fname'], unique=1)
    # ### end Alembic commands ###
